######################################################################
# Automatically generated by qmake (2.01a) Sun Mar 27 03:00:06 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += LoginForm.h
SOURCES += LoginForm.cpp main.cpp
